### PR TITLE
Expose the shape of props

### PR DESCRIPTION
**Pull request by orta**
Note, this is not Flow doing the work believe it or not, it's actually TypeScript.

screen shot 2016-12-27 at 11 46 34 am

### CODE REVIEW

**Comment by alloy** [comment]
Still, shouldn’t the type be imported from the exported flow types?

Also, what’s an `ArtistItem` vs an `Artist` ?

**Comment by alloy** [comment]
ping

**Comment by orta** [comment]
Ah yeah, should be `Artist` will fix in upcoming

**Comment by orta** [comment]
This is a bit more complex 

screen shot 2016-12-28 at 2 08 24 pm

They really should both be called `Artist` in this context

**Comment by alloy** [comment]
Ah yeah… guess we’ll need to get some Hungarian notation in there then :/ E.g. `ArtistContainer`

**Comment by orta** [comment]
I initially thought we could prefix the metaphysics types, but I think once graphql is in flow mainline, then it'll be less useful

**Pull request closed without merging**
